/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/neuron.glb -o components/NeuronModel.tsx -t 
*/

import { useGLTF } from '@react-three/drei'
import { JSX } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Electricity_geo_Electricity_0: THREE.Mesh
    Light_geo_Light_0: THREE.Mesh
    NeonPulse_geo_NeonPulse_0: THREE.Mesh
    Toon_geo_Toon_0: THREE.Mesh
    Toon_geo_Toon_0001: THREE.Mesh
    Toon_geo_Toon_0002: THREE.Mesh
    Toon_geo_Toon_0003: THREE.Mesh
    Toon_geo_Toon_0004: THREE.Mesh
    Toon_geo_Toon_0005: THREE.Mesh
    Toon_geo_Toon_0006: THREE.Mesh
  }
  materials: {
    Electricity: THREE.MeshStandardMaterial
    Light: THREE.MeshStandardMaterial
    NeonPulse: THREE.MeshStandardMaterial
    Toon: THREE.MeshStandardMaterial
  }
}

export function NeuronModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/neuron.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Electricity_geo_Electricity_0.geometry} material={materials.Electricity} />
      <mesh geometry={nodes.Light_geo_Light_0.geometry}>
        <meshStandardMaterial
          attach="material"
          color="#19e0aa"
          emissive="#19e0aa"
          emissiveIntensity={0.5}
          // roughness={0.2}
          // metalness={0.8}
        />
      </mesh>
      <mesh geometry={nodes.NeonPulse_geo_NeonPulse_0.geometry} material={materials.NeonPulse} />
      <mesh geometry={nodes.Toon_geo_Toon_0.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0001.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0002.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0003.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0004.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0005.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0006.geometry} material={materials.Toon} />
    </group>
  )
}

useGLTF.preload('/neuron.glb')
