/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 checkered_origami_ball.glb -k -t -T 
Files: checkered_origami_ball.glb [5.61MB] > D:\dev\psychology\psychology-portfolio\public\checkered_origami_ball-transformed.glb [220.63KB] (96%)
Author: Kea-Makerlab (https://sketchfab.com/Kea-Makerlab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/checkered-origami-ball-d53d4663ca7943c881a9a6d20cdc7e91
Title: Checkered origami ball
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JSX } from 'react'


type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['kea-checkered-ball-50k-textured_Material_u1_v1']: THREE.MeshStandardMaterial
  }
}

export function OrigamiBall(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/checkered_origami_ball.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} 
      rotation={[-Math.PI / 2, 0, 0]} 
      scale={0.12}
      material={materials['kea-checkered-ball-50k-textured_Material_u1_v1']} 
      >
        {/* <meshStandardMaterial
          attach="material"
          color="#19e0aa"
          emissive="#19e0aa"
          emissiveIntensity={0.5}
        // roughness={0.2}
        // metalness={0.8}
        /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/checkered_origami_ball-transformed.glb')
