/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paper_swan.glb -k -t 
Author: Zamia Studio (https://sketchfab.com/zamiastudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-folded-swan-origami-art-44c7cb7fc2574e0c86519ed6102653d0
Title: Paper Folded Swan Origami Art
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['01___Default']: THREE.MeshStandardMaterial
  }
}

export function PaperSwan(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/paper_swan.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={0.04} >
        <meshStandardMaterial
          attach="material"
          color="#dadada"
          // emissive="#19e0aa"
          // emissiveIntensity={0.5}
        // roughness={0.2}
        // metalness={0.8}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/paper_swan.glb')
